// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlUHUp8Pn7WjGEH1rzIxg6uFtUo70nFSc',
    appId: '1:279599943939:web:94a66f25ae0b39119b9936',
    messagingSenderId: '279599943939',
    projectId: 'scango-26160',
    authDomain: 'scango-26160.firebaseapp.com',
    storageBucket: 'scango-26160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-2IAofZ6Cew87YXvbXlbCrCtSPELMz0',
    appId: '1:279599943939:android:b48ce0035cddde5d9b9936',
    messagingSenderId: '279599943939',
    projectId: 'scango-26160',
    storageBucket: 'scango-26160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLm2NxyqHYU2n4Z0isd0kKgTaeuXTDHec',
    appId: '1:279599943939:ios:e48008afee72f4949b9936',
    messagingSenderId: '279599943939',
    projectId: 'scango-26160',
    storageBucket: 'scango-26160.appspot.com',
    iosClientId: '279599943939-3ffcdidscvj2lfjqirrvthg899esrrv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLm2NxyqHYU2n4Z0isd0kKgTaeuXTDHec',
    appId: '1:279599943939:ios:0af722e5922b567b9b9936',
    messagingSenderId: '279599943939',
    projectId: 'scango-26160',
    storageBucket: 'scango-26160.appspot.com',
    iosClientId: '279599943939-imk5mmcntvp32tmk05cdogtnv4bbdvr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
